import { useEffect, useMemo, useState } from 'react';
import { NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BarChart3, Bell, Building2, CalendarDays, Camera, Check, ChevronRight, CircleUserRound, Compass, Heart, HelpCircle, Home, Languages, LayoutDashboard, Map, MapPin, Menu, MessageCircle, MoreHorizontal, Plus, Search, Settings, Sparkles, Star, TicketCheck, Upload, Users, Utensils, X } from 'lucide-react';
import { destinations, experiences, messages, providers, reservations } from './data/mock';
import { Button, Fav, IconButton, LocationPill, Rating, SearchBar, SectionTitle } from './components/UI';

const heroImage='https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=2200&q=88';

function useFavorites(){
  const [favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('marocogo:favs')||'[]')}catch{return[]}});
  const toggle=(slug:string)=>setFavorites(prev=>{const next=prev.includes(slug)?prev.filter(x=>x!==slug):[...prev,slug];localStorage.setItem('marocogo:favs',JSON.stringify(next));return next});
  return {favorites,toggle};
}

function Logo({compact=false}:{compact?:boolean}){
  return <NavLink to="/" className="brand" aria-label="MarocoGO accueil"><img src={compact?'/logo/marocogo-symbol.png':'/logo/marocogo-full.png'} alt="MarocoGO"/></NavLink>
}

function TravelerHeader(){
  const [scrolled,setScrolled]=useState(false); const [menu,setMenu]=useState(false); const nav=useNavigate();
  useEffect(()=>{const f=()=>setScrolled(window.scrollY>24);f();window.addEventListener('scroll',f);return()=>window.removeEventListener('scroll',f)},[]);
  return <>
    <header className={`traveler-header ${scrolled?'scrolled':''}`}>
      <Logo/>
      <nav className="desktop-nav"><NavLink to="/explorer">Explorer</NavLink><NavLink to="/planifier">Planifier</NavLink><NavLink to="/carte">Carte</NavLink><NavLink to="/voyages">Mes voyages</NavLink></nav>
      <div className="header-actions"><IconButton icon={Search} label="Recherche" onClick={()=>nav('/recherche')}/><IconButton icon={Heart} label="Favoris" onClick={()=>nav('/favoris')}/><IconButton icon={Languages} label="FR"/><IconButton icon={CircleUserRound} label="Profil" onClick={()=>nav('/profil')}/><button className="menu-btn" onClick={()=>setMenu(true)}><Menu/></button></div>
    </header>
    {menu&&<div className="mobile-menu glass3"><button onClick={()=>setMenu(false)} className="close"><X/></button><Logo/><NavLink onClick={()=>setMenu(false)} to="/explorer">Explorer</NavLink><NavLink onClick={()=>setMenu(false)} to="/planifier">Planifier</NavLink><NavLink onClick={()=>setMenu(false)} to="/carte">Carte</NavLink><NavLink onClick={()=>setMenu(false)} to="/voyages">Mes voyages</NavLink><NavLink onClick={()=>setMenu(false)} to="/pro/connexion">Espace prestataire</NavLink></div>}
  </>
}

function MobileTravelerNav(){ return <nav className="mobile-dock glass1"><NavLink to="/explorer"><Compass/><span>Explorer</span></NavLink><NavLink to="/carte"><Map/><span>Carte</span></NavLink><NavLink to="/planifier"><Sparkles/><span>Voyage</span></NavLink><NavLink to="/favoris"><Heart/><span>Favoris</span></NavLink><NavLink to="/profil"><CircleUserRound/><span>Profil</span></NavLink></nav> }

function Footer(){return <footer className="site-footer"><div><Logo/><p>Voir. Ressentir. Découvrir. Voyager.</p></div><div><strong>Découvrir</strong><NavLink to="/destinations">Destinations</NavLink><NavLink to="/experiences">Expériences</NavLink><NavLink to="/restaurants">Restaurants</NavLink></div><div><strong>MarocoGO</strong><NavLink to="/aide">Aide</NavLink><NavLink to="/confidentialite">Confidentialité</NavLink><NavLink to="/conditions">Conditions</NavLink></div><div><strong>Professionnels</strong><NavLink to="/pro/connexion">Espace prestataire</NavLink><span>Français · Maroc</span></div></footer>}

function TravelerLayout({children}:{children:React.ReactNode}){return <><TravelerHeader/><main>{children}</main><Footer/><MobileTravelerNav/></>}

function DestinationCard({d,favs,toggle}:{d:any;favs:string[];toggle:(s:string)=>void}){const nav=useNavigate();return <article className="destination-card" onClick={()=>nav(`/destinations/${d.slug}`)}><img src={d.image} alt={d.name}/><div className="shade"/><div className="card-top"><span onClick={(e)=>e.stopPropagation()}><Fav active={favs.includes(d.slug)} onClick={()=>toggle(d.slug)}/></span></div><div className="card-bottom"><p>{d.region}</p><h3>{d.name}</h3><span>{d.tagline}</span></div></article>}

function ExperienceCard({e}:{e:any}){const nav=useNavigate();return <article className="experience-card" onClick={()=>nav(`/experiences/${e.slug}`)}><img src={e.image} alt={e.title}/><div className="experience-body"><div className="meta-row"><LocationPill city={e.city}/><Rating value={e.rating}/></div><h3>{e.title}</h3><p>{e.category} · {e.duration}</p><strong>{e.price} DH</strong></div></article>}

function ProviderCard({p}:{p:any}){const nav=useNavigate();const path=p.category==='Restaurant'?`/restaurants/${p.slug}`:p.category==='Guide'?`/guides/${p.slug}`:`/hebergements/${p.slug}`;return <article className="provider-card" onClick={()=>nav(path)}><img src={p.image} alt={p.name}/><div><div className="meta-row"><span className="eyebrow">{p.category}</span><Rating value={p.rating}/></div><h3>{p.name}</h3><p>{p.city}</p><strong>{p.priceLabel}</strong></div></article>}

function HomePage(){const {favorites,toggle}=useFavorites();const nav=useNavigate();return <TravelerLayout>
  <section className="hero" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.48)),url(${heroImage})`}}><div className="hero-content"><span className="hero-kicker">MAROCOGO</span><h1>Le Maroc,<br/>à votre rythme.</h1><p>Des lieux, des rencontres et des expériences qui donnent envie de partir.</p><div className="hero-actions"><Button onClick={()=>nav('/explorer')}>Commencer à explorer <ArrowRight size={18}/></Button><Button variant="glass" onClick={()=>nav('/planifier')}>Créer mon voyage</Button></div></div><div className="hero-search"><SearchBar onClick={()=>nav('/recherche')}/></div></section>
  <section className="section"><SectionTitle eyebrow="Choisir une direction" title="Des villes à vivre, pas seulement à visiter" action="Toutes les destinations"/><div className="destination-grid">{destinations.slice(0,6).map(d=><DestinationCard key={d.slug} d={d} favs={favorites} toggle={toggle}/>)}</div></section>
  <section className="section soft"><SectionTitle eyebrow="Selon votre envie" title="Le Maroc change de visage à chaque détour"/><div className="chips">{['Mer','Désert','Montagne','Culture','Médinas','Gastronomie','Nature','Aventure','Détente'].map(x=><button key={x} onClick={()=>nav(`/explorer?theme=${x}`)}>{x}</button>)}</div></section>
  <section className="section"><SectionTitle eyebrow="Sélection MarocoGO" title="Expériences à garder en mémoire" action="Voir les expériences"/><div className="three-grid">{experiences.slice(0,3).map(e=><ExperienceCard key={e.slug} e={e}/>)}</div></section>
  <section className="section split-feature"><div><p className="eyebrow">AUTOUR DE VOUS</p><h2>Découvrir ce qui se trouve juste à côté.</h2><p>MarocoGO ne demande votre position qu'au moment où vous choisissez de l'utiliser.</p><Button variant="glass" onClick={()=>nav('/carte')}><MapPin size={18}/> Ouvrir la carte</Button></div><div className="map-art"><span>Rabat</span><i/><span>Marrakech</span><i/><span>Fès</span></div></section>
  <section className="section plan-cta"><div><p className="eyebrow">VOTRE VOYAGE</p><h2>Quelques choix. Un itinéraire qui vous ressemble.</h2><p>Destination, dates, rythme, budget et envies. Vous gardez toujours le dernier mot.</p><Button onClick={()=>nav('/planifier')}>Planifier mon séjour <Sparkles size={17}/></Button></div></section>
</TravelerLayout>}

function CatalogPage({kind}:{kind:'destinations'|'experiences'|'hebergements'|'restaurants'|'guides'|'activites'}){const {favorites,toggle}=useFavorites();const title={destinations:'Destinations',experiences:'Expériences',hebergements:'Hébergements',restaurants:'Restaurants & cafés',guides:'Guides',activites:'Activités'}[kind];return <TravelerLayout><section className="page-hero-small"><p className="eyebrow">EXPLORER LE MAROC</p><h1>{title}</h1><p>Une sélection claire, pensée pour comparer sans vous perdre.</p></section><section className="section"><div className="filter-row"><button className="filter active">Tous</button><button className="filter">Les mieux notés</button><button className="filter">À proximité</button><button className="filter">Budget</button></div>{kind==='destinations'?<div className="destination-grid">{destinations.map(d=><DestinationCard key={d.slug} d={d} favs={favorites} toggle={toggle}/>)}</div>:kind==='experiences'||kind==='activites'?<div className="three-grid">{[...experiences,...experiences].map((e,i)=><ExperienceCard key={e.slug+i} e={e}/>)}</div>:<div className="provider-grid">{providers.filter(p=>kind==='restaurants'?p.category==='Restaurant':kind==='guides'?p.category==='Guide':p.category!=='Restaurant'&&p.category!=='Guide').concat(providers).slice(0,12).map((p,i)=><ProviderCard key={p.slug+i} p={p}/>)}</div>}</section></TravelerLayout>}

function ExplorerPage(){return <TravelerLayout><section className="page-hero-small"><p className="eyebrow">EXPLORER</p><h1>Qu'avez-vous envie de vivre ?</h1><p>Choisissez une ambiance, une ville ou simplement laissez-vous surprendre.</p><SearchBar/></section><section className="section"><div className="bento"><NavLink to="/destinations" className="bento-big"><img src={destinations[1].image}/><span>Destinations</span></NavLink><NavLink to="/experiences"><img src={experiences[2].image}/><span>Expériences</span></NavLink><NavLink to="/restaurants"><img src={providers[1].image}/><span>Restaurants</span></NavLink><NavLink to="/hebergements"><img src={providers[0].image}/><span>Hébergements</span></NavLink><NavLink to="/guides"><img src={providers[2].image}/><span>Guides</span></NavLink></div></section></TravelerLayout>}

function DestinationDetail(){const {slug}=useParams();const d=destinations.find(x=>x.slug===slug)||destinations[0];return <TravelerLayout><section className="detail-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.45)),url(${d.image})`}}><div><p>{d.region}</p><h1>{d.name}</h1><span>{d.tagline}</span></div></section><section className="section detail-copy"><div><p className="eyebrow">POURQUOI Y ALLER</p><h2>{d.description}</h2></div><div><p>Promenez-vous sans programme trop serré. Les meilleures découvertes sont souvent celles qui se trouvent entre deux étapes.</p><div className="chips">{d.tags.map(t=><button key={t}>{t}</button>)}</div></div></section><section className="section"><SectionTitle title={`À vivre à ${d.name}`}/><div className="three-grid">{experiences.slice(0,3).map(e=><ExperienceCard key={e.slug} e={{...e,city:d.name}}/>)}</div></section><section className="section"><SectionTitle title="Adresses sélectionnées"/><div className="provider-grid">{providers.slice(0,4).map(p=><ProviderCard key={p.slug} p={{...p,city:d.name}}/>)}</div></section></TravelerLayout>}

function ExperienceDetail(){const {slug}=useParams();const e=experiences.find(x=>x.slug===slug)||experiences[0];const [booked,setBooked]=useState(false);return <TravelerLayout><section className="entity-shell"><div className="entity-gallery"><img src={e.image}/></div><div className="entity-info"><LocationPill city={e.city}/><h1>{e.title}</h1><div className="meta-row"><Rating value={e.rating}/><span>{e.duration}</span><span>{e.category}</span></div><p>Une expérience en petit groupe, conçue pour prendre le temps de découvrir et échanger.</p><div className="booking-card glass2"><div><span>À partir de</span><strong>{e.price} DH</strong></div><Button onClick={()=>setBooked(true)}>{booked?<><Check size={18}/> Ajouté</>:<>Réserver</>}</Button></div></div></section></TravelerLayout>}

function ProviderDetail(){const {slug}=useParams();const p=providers.find(x=>x.slug===slug)||providers[0];const [reserved,setReserved]=useState(false);return <TravelerLayout><section className="entity-shell"><div className="entity-gallery"><img src={p.image}/></div><div className="entity-info"><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><div className="meta-row"><LocationPill city={p.city}/><Rating value={p.rating}/><span>{p.reviews} avis</span></div><p>{p.description}</p><h3>{p.priceLabel}</h3><div className="action-row"><Button onClick={()=>setReserved(true)}>{reserved?<><Check size={18}/> Demande envoyée</>:'Réserver'}</Button><Button variant="ghost"><MapPin size={18}/> Itinéraire</Button></div><div className="facts"><div><span>Langues</span><strong>FR · EN · AR</strong></div><div><span>Disponibilité</span><strong>Aujourd'hui</strong></div><div><span>Réponse</span><strong>Environ 1 h</strong></div></div></div></section><section className="section"><SectionTitle title="À propos"/><div className="detail-copy"><p>Les informations présentées dans cette version sont des données de démonstration. Elles illustrent la future fiche prestataire MarocoGO.</p><p>Services, horaires, accessibilité, contacts, disponibilité, galerie, carte et avis pourront ensuite être alimentés par le backend.</p></div></section></TravelerLayout>}

function MapPage(){const [selected,setSelected]=useState(destinations[0]);return <TravelerLayout><section className="map-page"><aside className="map-results glass2"><h1>Explorer la carte</h1><div className="filter-row"><button className="filter active">Tout</button><button className="filter">Manger</button><button className="filter">Dormir</button></div>{destinations.slice(0,5).map(d=><button className={`map-result ${selected.slug===d.slug?'active':''}`} onClick={()=>setSelected(d)} key={d.slug}><img src={d.image}/><span><strong>{d.name}</strong><small>{d.tagline}</small></span></button>)}</aside><div className="fake-map"><div className="map-label">Carte prototype · sans clé externe</div>{destinations.slice(0,7).map((d,i)=><button onClick={()=>setSelected(d)} key={d.slug} className="pin" style={{left:`${18+(i*11)%65}%`,top:`${18+(i*17)%60}%`}}><MapPin size={20}/></button>)}<div className="selected-pin glass2"><img src={selected.image}/><div><strong>{selected.name}</strong><span>{selected.tagline}</span></div></div></div></section></TravelerLayout>}

function PlannerPage(){const steps=['Destination','Dates','Voyageurs','Envies','Rythme','Budget','Itinéraire'];const [step,setStep]=useState(0);const [choice,setChoice]=useState('Marrakech');return <TravelerLayout><section className="planner"><div className="planner-progress">{steps.map((s,i)=><span key={s} className={i<=step?'active':''}>{i+1}</span>)}</div><div className="planner-card glass2"><p className="eyebrow">ÉTAPE {step+1} / {steps.length}</p><h1>{step===0?'Où souhaitez-vous commencer ?':step===6?'Votre première proposition':'Précisons votre voyage'}</h1>{step===0?<div className="choice-grid">{destinations.slice(0,6).map(d=><button className={choice===d.name?'selected':''} onClick={()=>setChoice(d.name)} key={d.slug}><img src={d.image}/><span>{d.name}</span></button>)}</div>:step===6?<div className="itinerary"><div><strong>Jour 1</strong><span>Arrivée, promenade et dîner local</span></div><div><strong>Jour 2</strong><span>Médina, atelier et terrasse au coucher du soleil</span></div><div><strong>Jour 3</strong><span>Excursion douce autour de {choice}</span></div></div>:<div className="form-grid"><label>Votre préférence<input placeholder={step===1?'8 – 12 octobre':step===2?'2 voyageurs':'Flexible'}/></label><label>Un détail utile<input placeholder="Optionnel"/></label></div>}<div className="planner-actions"><Button variant="ghost" onClick={()=>setStep(Math.max(0,step-1))} disabled={false}><ArrowLeft size={17}/> Retour</Button><Button onClick={()=>setStep(Math.min(steps.length-1,step+1))}>{step===steps.length-1?'Enregistrer le voyage':'Continuer'} <ArrowRight size={17}/></Button></div></div></section></TravelerLayout>}

function FavoritesPage(){const {favorites,toggle}=useFavorites();const items=destinations.filter(d=>favorites.includes(d.slug));return <TravelerLayout><section className="page-hero-small"><p className="eyebrow">VOTRE SÉLECTION</p><h1>Favoris</h1><p>Gardez les lieux qui vous donnent envie de revenir.</p></section><section className="section">{items.length?<div className="destination-grid">{items.map(d=><DestinationCard key={d.slug} d={d} favs={favorites} toggle={toggle}/>)}</div>:<EmptyState icon={Heart} title="Aucun favori pour le moment" text="Ajoutez des destinations et expériences pour les retrouver ici." action="Explorer" to="/explorer"/>}</section></TravelerLayout>}

function SearchPage(){const [q,setQ]=useState('');const results=useMemo(()=>destinations.filter(d=>(d.name+d.tags.join(' ')).toLowerCase().includes(q.toLowerCase())),[q]);return <TravelerLayout><section className="search-page"><div className="search-input-wrap"><Search/><input autoFocus placeholder="Destination, expérience, envie…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={()=>setQ('')}><X/></button></div><div className="search-results">{q?results.map(d=><NavLink to={`/destinations/${d.slug}`} key={d.slug}><img src={d.image}/><span><strong>{d.name}</strong><small>{d.tags.join(' · ')}</small></span><ChevronRight/></NavLink>):<><p className="eyebrow">SUGGESTIONS</p><div className="chips">{['Marrakech','Week-end mer','Désert','Gastronomie','Montagne'].map(x=><button onClick={()=>setQ(x)} key={x}>{x}</button>)}</div></>}</div></section></TravelerLayout>}

function EmptyState({icon:Icon,title,text,action,to}:{icon:any;title:string;text:string;action:string;to:string}){return <div className="empty-state"><Icon/><h2>{title}</h2><p>{text}</p><NavLink className="btn btn-primary" to={to}>{action}</NavLink></div>}

function SimpleTravelerPage({title,subtitle}:{title:string;subtitle:string}){return <TravelerLayout><section className="page-hero-small"><p className="eyebrow">MAROCOGO</p><h1>{title}</h1><p>{subtitle}</p></section><section className="section"><div className="simple-content"><h2>Une expérience conçue pour rester simple.</h2><p>Cette page est prête à être reliée au backend. La structure, les états et la navigation sont déjà en place dans cette version frontend.</p></div></section></TravelerLayout>}

function AuthPage({provider=false,signup=false}:{provider?:boolean;signup?:boolean}){const nav=useNavigate();return <div className="auth-shell"><div className="auth-visual" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.2),rgba(0,0,0,.5)),url(${destinations[2].image})`}}><Logo/><div><p className="eyebrow">MAROCOGO</p><h1>{provider?'Votre activité, mieux présentée.':'Le voyage commence ici.'}</h1></div></div><div className="auth-panel"><Logo/><div className="auth-box"><h2>{provider?'Connexion prestataire':signup?'Créer un compte':'Bon retour parmi nous'}</h2><p>{provider?'Gérez vos services, réservations et échanges.':'Retrouvez vos voyages et vos favoris.'}</p><label>Email<input type="email" placeholder="vous@exemple.com"/></label><label>Mot de passe<input type="password" placeholder="••••••••"/></label><Button onClick={()=>nav(provider?'/pro/tableau-de-bord':'/profil')}>{provider?'Accéder à mon espace':signup?'Créer mon compte':'Se connecter'}</Button>{!provider&&<button className="plain-link" onClick={()=>nav(signup?'/connexion':'/inscription')}>{signup?'J’ai déjà un compte':'Créer un compte'}</button>}<small>Prototype frontend : aucune authentification réelle n’est effectuée.</small></div></div></div>}

const proNav=[['/pro/tableau-de-bord',LayoutDashboard,'Tableau de bord'],['/pro/etablissement',Building2,'Établissement'],['/pro/services',TicketCheck,'Services'],['/pro/reservations',CalendarDays,'Réservations'],['/pro/disponibilites',CalendarDays,'Disponibilités'],['/pro/messages',MessageCircle,'Messages'],['/pro/avis',Star,'Avis'],['/pro/statistiques',BarChart3,'Statistiques'],['/pro/promotions',Sparkles,'Promotions'],['/pro/medias',Camera,'Médias'],['/pro/profil',CircleUserRound,'Profil'],['/pro/parametres',Settings,'Paramètres']] as const;

function ProviderLayout({children}:{children:React.ReactNode}){return <div className="pro-shell"><aside className="pro-sidebar glass2"><Logo compact/><nav>{proNav.map(([to,Icon,label])=><NavLink key={to} to={to}><Icon/><span>{label}</span></NavLink>)}</nav><NavLink to="/" className="back-public"><ArrowLeft/><span>Site public</span></NavLink></aside><div className="pro-main"><header className="pro-header"><div><span className="eyebrow">ESPACE PRESTATAIRE</span></div><div><button><Bell/></button><div className="avatar">YA</div></div></header>{children}</div><nav className="pro-mobile-dock glass1"><NavLink to="/pro/tableau-de-bord"><Home/><span>Accueil</span></NavLink><NavLink to="/pro/reservations"><CalendarDays/><span>Réservations</span></NavLink><NavLink className="pro-add" to="/pro/services/nouveau"><Plus/></NavLink><NavLink to="/pro/messages"><MessageCircle/><span>Messages</span></NavLink><NavLink to="/pro/profil"><CircleUserRound/><span>Profil</span></NavLink></nav></div>}

function Dashboard(){return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">LUNDI 5 OCTOBRE</p><h1>Bonjour Youssef.</h1><p>Voici ce qui mérite votre attention aujourd'hui.</p></div><Button><Plus size={17}/> Nouvelle disponibilité</Button></div><div className="kpi-grid"><Kpi label="Réservations aujourd'hui" value="3" note="2 confirmées"/><Kpi label="Nouveaux messages" value="2" note="À répondre"/><Kpi label="Note moyenne" value="4,9" note="182 avis"/><Kpi label="Taux de réponse" value="98%" note="Excellent"/></div><div className="pro-grid"><div className="panel"><div className="panel-head"><h2>Prochaines réservations</h2><NavLink to="/pro/reservations">Tout voir</NavLink></div>{reservations.slice(0,3).map(r=><div className="list-row" key={r.id}><div><strong>{r.guest}</strong><span>{r.service}</span></div><div><small>{r.date}</small><Status value={r.status}/></div></div>)}</div><div className="panel"><div className="panel-head"><h2>Activité récente</h2></div><div className="timeline"><p><i/>Nouvelle réservation de <strong>Yanis Dupont</strong><span>Il y a 12 min</span></p><p><i/>Un avis 5 étoiles a été publié<span>Il y a 2 h</span></p><p><i/>Votre galerie a été consultée 34 fois<span>Aujourd'hui</span></p></div></div></div></section></ProviderLayout>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Status({value}:{value:string}){return <span className={`status status-${value.toLowerCase().replace('à ','').replace('é','e').replace('é','e').replace(' ','-')}`}>{value}</span>}

function ReservationsPage(){const [items,setItems]=useState(reservations);const update=(id:string)=>setItems(it=>it.map(r=>r.id===id?{...r,status:r.status==='Nouvelle'?'Confirmée':'Terminée'}:r));return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">GESTION</p><h1>Réservations</h1><p>Suivez les demandes et confirmez chaque changement important.</p></div></div><div className="panel"><div className="filter-row"><button className="filter active">Toutes</button><button className="filter">Nouvelles</button><button className="filter">À venir</button></div>{items.map(r=><div className="reservation-row" key={r.id}><div><small>{r.id}</small><strong>{r.guest}</strong><span>{r.service}</span></div><div><span>{r.date}</span><strong>{r.total}</strong></div><Status value={r.status}/><button className="round-action" onClick={()=>update(r.id)}><ChevronRight/></button></div>)}</div></section></ProviderLayout>}

function MessagesPage(){const [selected,setSelected]=useState(messages[0]);return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">ÉCHANGES</p><h1>Messages</h1></div></div><div className="messages-layout panel"><aside>{messages.map(m=><button onClick={()=>setSelected(m)} className={selected.id===m.id?'active':''} key={m.id}><div className="avatar">{m.name.split(' ').map(x=>x[0]).join('')}</div><span><strong>{m.name}</strong><small>{m.preview}</small></span><em>{m.time}</em></button>)}</aside><div className="conversation"><div className="conversation-head"><strong>{selected.name}</strong><span>Réservation en cours</span></div><div className="bubble incoming">Bonjour, notre arrivée est prévue vers 18h. Est-ce que cela convient ?</div><div className="bubble outgoing">Bonjour, oui bien sûr. Nous vous accueillerons avec plaisir à partir de 18h.</div><div className="composer"><input placeholder="Écrire un message…"/><button><ArrowRight/></button></div></div></div></section></ProviderLayout>}

function EstablishmentPage(){const [saved,setSaved]=useState(false);return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">VOTRE VITRINE</p><h1>Établissement</h1><p>Les informations visibles publiquement sur MarocoGO.</p></div></div><form className="panel pro-form" onSubmit={e=>{e.preventDefault();setSaved(true)}}><div className="form-grid"><label>Nom<input defaultValue="Riad Azur"/></label><label>Catégorie<select defaultValue="Riad"><option>Riad</option><option>Hôtel</option><option>Restaurant</option><option>Guide</option></select></label><label className="full">Description<textarea defaultValue="Un riad calme au cœur de la médina, patio lumineux et terrasse panoramique."/></label><label>Ville<input defaultValue="Marrakech"/></label><label>Téléphone<input defaultValue="+212 6 00 00 00 00"/></label><label>Email<input defaultValue="bonjour@riadazur.ma"/></label><label>Langues<input defaultValue="Français, anglais, arabe"/></label></div><div className="form-actions">{saved&&<span className="save-ok"><Check/> Modifications enregistrées</span>}<Button type="submit">Enregistrer</Button></div></form></section></ProviderLayout>}

function ServicesPage({newService=false}:{newService?:boolean}){const [count,setCount]=useState(3);return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">OFFRE</p><h1>{newService?'Nouveau service':'Services'}</h1><p>Présentez clairement ce que les voyageurs peuvent réserver.</p></div>{!newService&&<Button onClick={()=>setCount(c=>c+1)}><Plus/> Ajouter</Button>}</div>{newService?<div className="panel pro-form"><div className="form-grid"><label>Nom du service<input placeholder="Ex. Suite Terrasse"/></label><label>Prix<input placeholder="980 DH"/></label><label>Durée<input placeholder="1 nuit"/></label><label>Capacité<input placeholder="2 personnes"/></label><label className="full">Description<textarea placeholder="Décrivez l'expérience simplement…"/></label></div><Button>Créer le service</Button></div>:<div className="service-grid">{Array.from({length:count}).map((_,i)=><div className="panel service-card" key={i}><img src={providers[i%providers.length].image}/><div><span className="status">Actif</span><h3>{['Suite Patio','Dîner découverte','Visite médina','Nouvelle expérience'][i%4]}</h3><p>{i%2?'3 h · 2 à 8 personnes':'1 nuit · 2 personnes'}</p><strong>{i%2?'440 DH':'1 060 DH'}</strong></div><button><MoreHorizontal/></button></div>)}</div>}</section></ProviderLayout>}

function GenericProPage({title,icon:Icon}:{title:string;icon:any}){return <ProviderLayout><section className="pro-page"><div className="pro-title"><div><p className="eyebrow">ESPACE PRESTATAIRE</p><h1>{title}</h1><p>Interface prête pour la connexion au futur backend MarocoGO.</p></div></div><div className="panel generic-pro"><Icon/><h2>{title}</h2><p>Cette section possède déjà la structure visuelle et responsive du frontend professionnel.</p><div className="mock-bars"><i/><i/><i/><i/></div></div></section></ProviderLayout>}

function NotFound(){return <TravelerLayout><section className="notfound"><span>404</span><h1>Cette route n'existe pas.</h1><p>Le voyage continue ailleurs.</p><NavLink className="btn btn-primary" to="/">Retour à l'accueil</NavLink></section></TravelerLayout>}

export default function App(){const location=useLocation();useEffect(()=>{window.scrollTo(0,0)},[location.pathname]);return <Routes>
  <Route path="/" element={<HomePage/>}/><Route path="/explorer" element={<ExplorerPage/>}/><Route path="/destinations" element={<CatalogPage kind="destinations"/>}/><Route path="/destinations/:slug" element={<DestinationDetail/>}/><Route path="/experiences" element={<CatalogPage kind="experiences"/>}/><Route path="/experiences/:slug" element={<ExperienceDetail/>}/><Route path="/hebergements" element={<CatalogPage kind="hebergements"/>}/><Route path="/hebergements/:slug" element={<ProviderDetail/>}/><Route path="/restaurants" element={<CatalogPage kind="restaurants"/>}/><Route path="/restaurants/:slug" element={<ProviderDetail/>}/><Route path="/guides" element={<CatalogPage kind="guides"/>}/><Route path="/guides/:slug" element={<ProviderDetail/>}/><Route path="/activites" element={<CatalogPage kind="activites"/>}/><Route path="/carte" element={<MapPage/>}/><Route path="/planifier" element={<PlannerPage/>}/><Route path="/favoris" element={<FavoritesPage/>}/><Route path="/recherche" element={<SearchPage/>}/><Route path="/connexion" element={<AuthPage/>}/><Route path="/inscription" element={<AuthPage signup/>}/><Route path="/profil" element={<SimpleTravelerPage title="Votre profil" subtitle="Vos préférences, réservations et informations de voyage."/>}/><Route path="/voyages" element={<SimpleTravelerPage title="Mes voyages" subtitle="Retrouvez vos itinéraires enregistrés et vos prochaines escapades."/>}/><Route path="/voyages/:id" element={<SimpleTravelerPage title="Voyage au Maroc" subtitle="Votre itinéraire jour par jour."/>}/><Route path="/reservations" element={<SimpleTravelerPage title="Mes réservations" subtitle="Vos réservations regroupées au même endroit."/>}/><Route path="/reservations/:id" element={<SimpleTravelerPage title="Détail de la réservation" subtitle="Toutes les informations utiles avant votre expérience."/>}/><Route path="/aide" element={<SimpleTravelerPage title="Comment pouvons-nous aider ?" subtitle="Retrouvez les réponses essentielles pour utiliser MarocoGO sereinement."/>}/><Route path="/confidentialite" element={<SimpleTravelerPage title="Confidentialité" subtitle="Des données demandées uniquement lorsque cela est nécessaire."/>}/><Route path="/conditions" element={<SimpleTravelerPage title="Conditions d'utilisation" subtitle="Les règles essentielles, écrites pour rester compréhensibles."/>}/>
  <Route path="/pro/connexion" element={<AuthPage provider/>}/><Route path="/pro/tableau-de-bord" element={<Dashboard/>}/><Route path="/pro/etablissement" element={<EstablishmentPage/>}/><Route path="/pro/services" element={<ServicesPage/>}/><Route path="/pro/services/nouveau" element={<ServicesPage newService/>}/><Route path="/pro/services/:id" element={<ServicesPage newService/>}/><Route path="/pro/reservations" element={<ReservationsPage/>}/><Route path="/pro/reservations/:id" element={<ReservationsPage/>}/><Route path="/pro/messages" element={<MessagesPage/>}/><Route path="/pro/messages/:id" element={<MessagesPage/>}/><Route path="/pro/disponibilites" element={<GenericProPage title="Disponibilités" icon={CalendarDays}/>}/><Route path="/pro/avis" element={<GenericProPage title="Avis" icon={Star}/>}/><Route path="/pro/statistiques" element={<GenericProPage title="Statistiques" icon={BarChart3}/>}/><Route path="/pro/promotions" element={<GenericProPage title="Promotions" icon={Sparkles}/>}/><Route path="/pro/medias" element={<GenericProPage title="Médias" icon={Upload}/>}/><Route path="/pro/profil" element={<GenericProPage title="Profil" icon={CircleUserRound}/>}/><Route path="/pro/parametres" element={<GenericProPage title="Paramètres" icon={Settings}/>}/><Route path="/pro/aide" element={<GenericProPage title="Aide" icon={HelpCircle}/>}/>
  <Route path="*" element={<NotFound/>}/>
</Routes>}
